language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r umonya/requirements.txt --use-mirrors
    - umonya/manage.py syncdb --noinput
	- umonya/manage.py migrate
script: umonya/manage.py test main
